#!/usr/bin/env node
var Handlebars = require("handlebars");


// Check for filename
if (process.argv.length < 3) {
    console.log("Usage: node " + process.argv[1] + " mustache_file data_file");
    process.exit(1);
}

var fs = require("fs"),
    template = process.argv[2],
    data_file = process.argv[3];
    

fs.readFile(template, 'utf8', function (err, data) {
    if (err) throw err;

    var compiled = Handlebars.compile(data);

    fs.readFile(data_file, 'utf8', function (err, data) {
        if (err) throw err;

        var input = require("js-yaml").load(data);

        console.log(compiled(input));
    });

});


